name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # O master, dependiendo de cómo se llame tu rama principal

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: ⚙️ Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Usa la versión de Node que estés utilizando
        
    - name: 📦 Install Dependencies
      run: npm install
      
    - name: 🏗️ Build Project
      run: npm run build
      
    - name: 📂 Sync files to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/ # Astro genera los archivos aquí
        server-dir: ./ # Esto asume que el usuario FTP cae directo en public_html
